# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0744654ff689b046df6565521ee240b382ca0c9f5642eadc0886be5e1c281416d02afa03503c3889611b7074b372f80230d12cbda311a3b3feb456082e4d556

test:
  secret_key_base: 391ad8175e020af6df75e21b812f636a92d6894fe3bc7024c125910a248a61237bf3a393a2f8c7fbfb9a65d2715d8711f79f622822a251960da3c1dfbf1a7711

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
